version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pleasure_message
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build: .
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/pleasure_message
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/pleasure_message
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=postgres
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration
      - JWT_SECRET=mysecretisjustlongenoughforhmac512-01234567890123456789012345678
      - EXPIRATION=28800
      - CONTEXT_PATH=/api
      - PORT=8080
      - SWAGGER_PATH=/swagger-ui.html
    depends_on:
      - postgres
    ports:
      - "8080:8081"
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge
