version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pleasure_message
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pleasure_message"]
      interval: 30s
      retries: 5
      timeout: 10s

  app:
    build: .
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/pleasure_message
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/pleasure_message
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=postgres
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge
