spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30s
      min-idle-time: 5s
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    locations: ${SPRING_FLYWAY_LOCATIONS}
    baseline-on-migrate: true
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}
    url: ${SPRING_FLYWAY_URL}

server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH}
#http://127.0.0.1:35153/webjars/swagger-ui/index.html
springdoc:
  swagger-ui:
    path: ${SWAGGER_PATH}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${EXPIRATION}