apiVersion: apps/v1
kind: Deployment
metadata:
  name: pleasure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pleasure-app
  template:
    metadata:
      labels:
        app: pleasure-app
    spec:
      containers:
        - name: pleasure-app
          image: mikhail199546399/pleasure:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_R2DBC_URL
              value: "r2dbc:postgresql://postgres:5432/pleasure_message"
            - name: SPRING_R2DBC_USERNAME
              value: "postgres"
            - name: SPRING_R2DBC_PASSWORD
              value: "postgres"
            - name: SPRING_FLYWAY_URL
              value: "jdbc:postgresql://postgres:5432/pleasure_message"
            - name: SPRING_FLYWAY_ENABLED
              value: "true"
            - name: SPRING_FLYWAY_USER
              value: "postgres"
            - name: SPRING_FLYWAY_PASSWORD
              value: "postgres"
            - name: SPRING_FLYWAY_LOCATIONS
              value: "classpath:db/migration"
            - name: JWT_SECRET
              value: "mysecretisjustlongenoughforhmac512-01234567890123456789012345678"
            - name: EXPIRATION
              value: "28800"
            - name: CONTEXT_PATH
              value: "/api"
            - name: PORT
              value: "8080"
            - name: SWAGGER_PATH
              value: "/swagger-ui.html"
---
apiVersion: v1
kind: Service
metadata:
  name: pleasure-app
spec:
  ports:
    - port: 8080
      targetPort: 8081
  selector:
    app: pleasure-app